### PR TITLE
Enhancement for the project

### PR DESCRIPTION
**Pull request by elton2048**
This pull request is based on the version from @izimobil which includes the implementation for delete view. It also includes the support for dynamic version and some test cases (May not completed) for the project.

### CODE REVIEW

**Comment by douglasmiranda** [comment]
WOW lots of contributions.

Thanks, I will review and merge xD

**Comment by harikvpy** [comment]
What's the status of this PR? Any chance of it getting merged soon? Tks.

**Comment by douglasmiranda** [comment]
Have you tried his PR? I didn't have the time to review, I'm accepting all the help I can to merge things more quickly.

**Comment by harikvpy** [comment]
I'm trying it now. Couple of issues come to mind immediately:

- The widget, while being really cool, has the fine-uploader template script defined in the widget template. This means that if a form defines to instances of the same widget, the template script will be defined twice in the final emitted html file. Not a big issue, but one that can be avoided by using a javascript file. (Django normalizes the final media output for a form by removing duplicate script files)

- In the widget template, delete URL reverse('django_fine_uploader:delete') requires that it is defined without any named URL arguments. However, the FineUploaderDeleteView tries to retrieve the guid of the file to be deleted from the named argument 'qquuid'. This would,  I believe would break the code.

- Support for fine-uploader session initialization list would be great, but this is an improvement item.

Will update more findings as I discover them.

**Comment by harikvpy** [comment]
Update:

- On the first point -- I was wrong. Javascript templates are typically not embedded into a JS source file and therefore keeping it in the widget template makes sense.
- Delete URL is also fine. I didn't look carefully at the URL declaration where the <uuid> named parameter is embedded within another unnamed regex pattern as it's done in the sample code. It'll be great to call this out in the code.

One issue that I have discovered so far is with FineUploaderDeleteView. Both the post() and delete() methods `raise HttpResponseBadRequest()`. It should be `return HttpResponseBadRequest()` instead.

You can merge the code while fixing this. Tests are necessary, but since the original code does not have any, there's no regression there. Perhaps someday I'll get around to writing some.

Cheers.

**Pull request merged**
